"""Mirror Google Fonts locally — byte-identical rendering, zero visual drift.

The web app currently loads:
  https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900
    &family=Inter+Tight:wght@500;600;700;800
    &family=JetBrains+Mono:wght@400;500
    &display=swap

This script:
  1. Fetches Google's CSS as a modern Chrome browser (so we get woff2,
     not legacy formats).
  2. Parses out every `src: url(https://fonts.gstatic.com/...woff2)` URL.
  3. Downloads each WOFF2 binary verbatim. The WOFF2 file IS the font —
     using the same bytes guarantees identical glyph shapes, hinting,
     and metrics.
  4. Rewrites the CSS to point at local `/fonts/*.woff2` URLs.
  5. Writes everything to web/public/fonts/.

Output:
  web/public/fonts/fonts.css            (rewritten, same @font-face rules)
  web/public/fonts/*.woff2              (binary-identical to Google's)

Visual result: rendering is identical because (a) the WOFF2 bytes are
identical, (b) the @font-face declarations (font-family, font-weight,
font-style, font-display, unicode-range) are preserved exactly. The
only thing that changes is the URL prefix.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import httpx

OUT_DIR = Path(__file__).resolve().parent.parent / "web" / "public" / "fonts"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Send a modern Chrome User-Agent so Google returns the latest woff2 v33+
# files (not legacy woff or unicode-range-less files for older browsers).
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

# The exact Google Fonts query string the SPA currently uses. Keep this in
# lock-step with the <link> in web/index.html — if the SPA requests new
# weights, re-run this script.
GF_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;500;600;700;800;900"
    "&family=Inter+Tight:wght@500;600;700;800"
    "&family=JetBrains+Mono:wght@400;500"
    "&display=swap"
)

# URL regex inside @font-face src declarations. Google emits:
#   src: url(https://fonts.gstatic.com/s/inter/v[N]/...woff2) format('woff2');
_URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)")


def _local_filename(gstatic_url: str) -> str:
    """Derive a local filename from a fonts.gstatic.com URL.

    Example URL:
      https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50ojvT.woff2

    We keep the family directory + version + filename so different versions
    don't collide:
      inter-v18-UcCO3FwrK3iLTeHuS_nVMrMxCp50ojvT.woff2
    """
    # Strip the prefix and split.
    path = gstatic_url.split("fonts.gstatic.com/s/")[1]
    # e.g. "inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50ojvT.woff2"
    family, version, file = path.split("/")
    name = file.rsplit(".", 1)[0]
    return f"{family}-{version}-{name}.woff2"


def main() -> int:
    print(f"GET {GF_CSS_URL}")
    with httpx.Client(headers={"User-Agent": UA}, timeout=30.0) as c:
        r = c.get(GF_CSS_URL)
        r.raise_for_status()
        css = r.text

        urls = sorted(set(_URL_RE.findall(css)))
        print(f"Found {len(urls)} WOFF2 source URLs")

        url_map: dict[str, str] = {}
        for u in urls:
            local = _local_filename(u)
            out_path = OUT_DIR / local
            if out_path.exists() and out_path.stat().st_size > 0:
                print(f"  cached  /fonts/{local}")
            else:
                resp = c.get(u)
                resp.raise_for_status()
                out_path.write_bytes(resp.content)
                print(f"  fetched /fonts/{local}  ({len(resp.content):,} bytes)")
            url_map[u] = f"/fonts/{local}"

    # Rewrite CSS: every fonts.gstatic.com URL → local /fonts/* URL.
    rewritten = css
    for src, dst in url_map.items():
        rewritten = rewritten.replace(src, dst)

    css_path = OUT_DIR / "fonts.css"
    # Prepend an idempotent header so we know the file was generated.
    header = (
        "/* Auto-generated by scripts/mirror_google_fonts.py.\n"
        " * Source: " + GF_CSS_URL + "\n"
        " * Rendering: byte-identical to Google Fonts (same WOFF2 binaries,\n"
        " * same @font-face declarations, only URLs rewritten to /fonts/*).\n"
        " * Re-run the script when SPA font weights change.\n"
        " */\n"
    )
    css_path.write_text(header + rewritten, encoding="utf-8")
    print(f"\nWROTE  {css_path}  ({len(rewritten):,} bytes)")
    print(f"WROTE  {len(url_map)} woff2 files in {OUT_DIR}")
    print("\nNEXT STEPS:")
    print("  1. Replace the <link rel=stylesheet href=fonts.googleapis.com...> in")
    print("     web/index.html with: <link rel=stylesheet href=/fonts/fonts.css>")
    print("  2. Remove fonts.googleapis.com + fonts.gstatic.com from nginx CSP.")
    print("  3. Drop the preconnect/dns-prefetch tags for those origins.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
